### ISSUE TITLE
Verb list page - Allow deselecting all verbs, Allow selecting all verbs

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/english-quiz#11]
I thin we could have an upper checkbox where ticking you could get all selected and unticking you get everything wiped.

It could be a three state checkbox, marked --> all selected, gray marked --> some checks selected, not mark --> no verbs selected

**Comment by JTrillo** [comment]
Okay I have a question. If the upper checkbox is gray marked and you tick on it, all other verbs get selected or deselected?

**Comment by brauliodiez** [comment]
I would follow same behavior as in GMail, if you do that by mistake you can click the cancel button and go back

What do you think?

**Comment by JTrillo** [comment]
I like the idea

**Comment by JTrillo** [comment]
What do you think about this approach?
![verbListSelection](https://user-images.githubusercontent.com/33926302/97628972-b6f08a80-1a2d-11eb-92ae-da6641a575af.gif)

**Comment by brauliodiez** [comment]
Looks great,

We will have to work on the ui layout later on, but is great

**Comment by JTrillo** [comment]
I'm gonna create the PR then :)
