### ISSUE TITLE
Redesign main menu

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/english-quiz#113]
Now is hard for a new user to know what to do and how the application works

**Comment by gfmarcos** [comment]
Hola @brauliodiez !!

Te indico URL de prototipo con propuesta de solución al inconveniente detectado.

Para tener una experiencia lo más real posible, el prototipo implementa interacción, por lo que hace todo lo que se supone debe hacer.

[Prototipo - Redesign main menu](https://framer.com/share/English-Quiz--2cGTsdE9fnaVz6yvEa3g/wqlj_i13F#wqlj_i13F)

Espero feedback tanto del equipo como de ti, muchas gracias!!

**Comment by brauliodiez** [comment]
Tiene muy buena pinta
