### ISSUE TITLE
Create theme

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/english-quiz#13]
This issue is just to create the application mui theme + main page, attached more info just to get into context.

As soon as we get the theme done, I will open more issue to build the layout of each page.

![image (1)](https://user-images.githubusercontent.com/1457912/97107030-963ed280-16c5-11eb-8c9d-1a0f122eddb3.png)
![image (2)](https://user-images.githubusercontent.com/1457912/97107031-976fff80-16c5-11eb-9f4b-2571cffe445b.png)
![image](https://user-images.githubusercontent.com/1457912/97107032-98089600-16c5-11eb-86e3-eaf8efd85d9e.png)

![image](https://user-images.githubusercontent.com/1457912/97859218-96138800-1d00-11eb-936f-badb3a2aa72c.png)

**Comment by Firenz** [comment]
Please assign this issue to me!
