### ISSUE TITLE
Include pictures for missing verb icons

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/english-quiz#40]
get them from flat icon

**Comment by JTrillo** [comment]
We need 10/12 more premium icons:

| Verb                | Link                                                           |
|---------------------|----------------------------------------------------------------|
| flee (huir)         | https://www.flaticon.com/premium-icon/evacuation_3045277       |
| lay                 | https://www.flaticon.com/premium-icon/chicken_3061655          |
| put                 | https://www.flaticon.com/premium-icon/put-on-deodorant_1686012 |
| say                 | https://www.flaticon.com/premium-icon/talk_1989975             |
| sit                 | https://www.flaticon.com/premium-icon/sitting_3284707          |
| smell               | https://www.flaticon.com/premium-icon/smell_3269952            |
| sow (sembrar)       | https://www.flaticon.com/premium-icon/sow_3397582              |
| spit                | https://www.flaticon.com/premium-icon/spitting_3736124         |
| spoil (estropearse) | https://www.flaticon.com/premium-icon/burger_4117204           |
| steal               | https://www.flaticon.com/premium-icon/thief_2267675            |
| stink               | https://www.flaticon.com/premium-icon/foot_3300888             |
| swear               | https://www.flaticon.com/premium-icon/oath_4078623             |
| sweep               | https://www.flaticon.com/premium-icon/sweeping_2955705         |
| tread               | https://www.flaticon.com/premium-icon/step_1184701             |
| understand          | https://www.flaticon.com/premium-icon/idea_2436837             |
| upset               | https://www.flaticon.com/premium-icon/upset_1533764            |
| wear                | https://www.flaticon.com/premium-icon/casual_2853377           |
| weave               | https://www.flaticon.com/premium-icon/weave_2769681            |
| wring               | https://www.flaticon.com/premium-icon/wring_2042372            |

**Comment by brauliodiez** [comment]
Just added them, thanks !!!
