### ISSUE TITLE
Check playing sounds (verb form)

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/english-quiz#6]
We will add verb sounds and the user would be able to play them, check how this works

Important just test.with some generic verbs, we will add the real sound later on (or if you find some auto dictator that record output in mp4 that would be great)

**Comment by albertocaparros** [comment]
Did a bit of research and there's this Web Api for Speech: https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis

Used this react wrapper for testing, there's a button that reads the verb in the solution. Speech-to-test seems to work decently well if we want to add that in the future. 
Github: https://github.com/MikeyParton/react-speech-kit
Demo: https://mikeyparton.github.io/react-speech-kit/

If it looks good to you i'll make this feature a new component in test-verb-forms.
